### ISSUE TITLE
Microfilm database search results are unresponsive

### ISSUE THREAD

**Issue by danhorst** [ndlib/DLT-planning#1]
The [medieval microfilm database](http://microfilms-and-facsimiles.medieval.library.nd.edu/) search results do not behave correctly. Regardless of the query parameters in set in the URL (keyword, facet, pagination, etc.) the same 10 result are always displayed.

![incorrect-query-enforcement](https://cloud.githubusercontent.com/assets/2133/7709281/f85dcdf0-fe29-11e4-9026-88b5e877afbf.png)

**Comment by cdeluca495** [comment]
Could this be a solr indexing issue?


*Chris DeLuca*
*Lead Digital Library QA Developer**Hesburgh Libraries*
*University of Notre Dame*
208 Hesburgh Library
Notre Dame, IN 46556
*o:* 574-631-1388
*e: *cdeluca1@nd.edu

**Comment by danhorst** [comment]
It is conceivable that all the fields are being indexed incorrectly but I don’t think that is the problem. It is acting like there is an issue passing information between Rails and Solr, possibly the query handler.

**Comment by cdeluca495** [comment]
Changes to the catalog controller and solr indexer were made.  This was verified and deployed to production on 5/27/15.
