### ISSUE TITLE
Improve error handling in RBSC finding aid site generation

### ISSUE THREAD

**Issue by danhorst** [ndlib/DLT-planning#10]
The [RBSC Finding Aid website](https://rbsc.library.nd.edu/) went through a nightly update during an unplanned outage of file downloads in CurateND. The result was an entirely blank web page. Guard against this happening again.

**Comment by danhorst** [comment]
@ruthtillman I believe this has been addressed. The mode of failure hasn’t been tested as the download functions have been restored.

**Comment by ruthtillman** [comment]
Thank you, Dan.
