### ISSUE TITLE
Export list of ARCH-SEASIDE PIDs

### ISSUE THREAD

**Issue by danhorst** [ndlib/DLT-planning#3]
We would like to have a full list of the PIDs of the items in the Seaside Research Portal. Having a list of identifiers eliminates the need for a resource index for the [metadata export](https://github.com/ndlib/DLT-planning/issues/2).

**Comment by dbrower** [comment]
I emailed a list to you. It is from March 13, 2015. I am generating a newer one right now. I believe the list contains every PID in fedora (they are 1 per line, and there are about 17k lines).
