### ISSUE TITLE
Improve RBSC Finding Aid Display Application Import Process

### ISSUE THREAD

**Issue by danhorst** [ndlib/DLT-planning#5]
The Solr query that fetches documents for import into the RBSC finding aid application (repo: rbsc_findingaid_management; not on Github) does not support result pagination.
- [x] Traverse the paginated response from Solr to retrieve all results matching the query. @dbrower has done this before.
- [x] Remove hard limit of 200

**Comment by dbrower** [comment]
This is where I dealt with solr paging before. May or may not be helpful. For example, you probably can process everything inline, whereas the code linked to just makes a giant list.

https://github.com/vecnet/vecnet-dl/blob/master/app/controllers/harvest_controller.rb#L40-L57

**Comment by banurekha** [comment]
Worked on the patch and checked in

**Comment by danhorst** [comment]
Deployed to https://rbsc.library.nd.edu/
